name: Norminette-beta CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    with:
      python-version: '3.x'
      architecture: 'x64'
    - name: configure
      run: |
      python3 -m pip install --upgrade pip setuptools
      sudo mkdir -p /usr/local/share/norminette-beta && cd /usr/local/share/norminette-beta
      python3 -m venv venv
      source venv/bin/activate
      pip install norminette
      ln -s /usr/local/share/norminette-beta/venv/bin/norminette /usr/local/bin/norminette-beta
