name: Test build on Ubuntu based systems.

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SDL2_CONFIG: /home/runner/work/Doom-Nukem/Doom-Nukem/SDL2/sdl2-config
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
